"""Git hooks management — install/remove auto-sync hooks.

Hooks:
  post-commit   → tws-graph sync (background)
  post-merge    → tws-graph sync (background)
  post-checkout → tws-graph sync (background)

Each hook script is idempotent: install twice produces one hook; remove
cleans up only the TWS-managed block.
"""

from __future__ import annotations

import os
import stat
import sys

HOOK_NAMES = ("post-commit", "post-merge", "post-checkout")

# Markers used to delimit TWS-managed sections in hook scripts
MARKER_BEGIN = "# >>> tws-graph auto-sync >>>"
MARKER_END = "# <<< tws-graph auto-sync <<<"

HOOK_SCRIPT = r"""#!/bin/bash
# >>> tws-graph auto-sync >>>
# Auto-generated by tws-graph hooks install
# Runs tws-graph sync in background after git operations
(
    tws_graph=$(which tws-graph 2>/dev/null || echo "")
    if [ -z "$tws_graph" ]; then
        # Try installed package path
        tws_graph=$(python -m tws_graph 2>/dev/null && echo "python -m tws_graph" || echo "")
    fi
    if [ -n "$tws_graph" ]; then
        $tws_graph sync . &>/dev/null &
    fi
) &
# <<< tws-graph auto-sync <<<
""".strip()


def _find_git_dir(root: str) -> str | None:
    """Find the .git directory from a project root."""
    git_dir = os.path.join(root, ".git")
    if os.path.isdir(git_dir):
        return git_dir
    # Check for worktree or submodule (gitdir: path)
    git_file = os.path.join(root, ".git")
    if os.path.isfile(git_file):
        try:
            with open(git_file, "r") as f:
                content = f.read().strip()
            if content.startswith("gitdir:"):
                worktree_path = content[7:].strip()
                if os.path.isdir(worktree_path):
                    return worktree_path
        except OSError:
            pass
    return None


def install_hooks(project_root: str) -> tuple[int, int]:
    """Install tws-graph sync hooks in the git repo.

    Args:
        project_root: Path to the git working tree root.

    Returns:
        (installed, skipped) counts.
    """
    git_dir = _find_git_dir(project_root)
    if not git_dir:
        raise FileNotFoundError(
            f"No .git directory found at {project_root}. "
            f"Run this command from within a git repository."
        )

    hooks_dir = os.path.join(git_dir, "hooks")
    os.makedirs(hooks_dir, exist_ok=True)

    installed = 0
    skipped = 0

    for hook_name in HOOK_NAMES:
        hook_path = os.path.join(hooks_dir, hook_name)

        # Check if already installed
        if os.path.isfile(hook_path):
            with open(hook_path, "r", encoding="utf-8") as f:
                existing = f.read()
            if MARKER_BEGIN in existing:
                skipped += 1
                continue

        # Append or create
        content = HOOK_SCRIPT
        if os.path.isfile(hook_path):
            with open(hook_path, "r", encoding="utf-8") as f:
                existing = f.read().rstrip()
            if existing:
                content = f"{existing}\n\n{HOOK_SCRIPT}"

        with open(hook_path, "w", encoding="utf-8") as f:
            f.write(content)
            f.write("\n")

        # Make executable on Unix
        try:
            st = os.stat(hook_path)
            os.chmod(hook_path, st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        except OSError:
            pass  # Windows: chmod +x is a no-op but shouldn't crash

        installed += 1

    return installed, skipped


def remove_hooks(project_root: str) -> int:
    """Remove tws-graph sync hooks from the git repo.

    Args:
        project_root: Path to the git working tree root.

    Returns:
        Number of hooks cleaned.
    """
    git_dir = _find_git_dir(project_root)
    if not git_dir:
        raise FileNotFoundError(
            f"No .git directory found at {project_root}."
        )

    hooks_dir = os.path.join(git_dir, "hooks")
    if not os.path.isdir(hooks_dir):
        return 0

    cleaned = 0

    for hook_name in HOOK_NAMES:
        hook_path = os.path.join(hooks_dir, hook_name)
        if not os.path.isfile(hook_path):
            continue

        with open(hook_path, "r", encoding="utf-8") as f:
            content = f.read()

        if MARKER_BEGIN not in content:
            continue

        # Remove the TWS-managed block and surrounding blank lines
        import re
        pattern = rf"\n*\n*{re.escape(MARKER_BEGIN)}.*?{re.escape(MARKER_END)}\n*"
        new_content = re.sub(pattern, "", content, flags=re.DOTALL).strip()

        if new_content:
            with open(hook_path, "w", encoding="utf-8") as f:
                f.write(new_content)
                f.write("\n")
        else:
            # Empty after removing TWS block → delete the hook file
            os.remove(hook_path)

        cleaned += 1

    return cleaned


def status_hooks(project_root: str) -> dict[str, bool]:
    """Check which hooks are installed.

    Returns:
        {hook_name: is_installed}
    """
    git_dir = _find_git_dir(project_root)
    status = {name: False for name in HOOK_NAMES}

    if not git_dir:
        return status

    hooks_dir = os.path.join(git_dir, "hooks")
    if not os.path.isdir(hooks_dir):
        return status

    for hook_name in HOOK_NAMES:
        hook_path = os.path.join(hooks_dir, hook_name)
        if os.path.isfile(hook_path):
            with open(hook_path, "r", encoding="utf-8") as f:
                status[hook_name] = MARKER_BEGIN in f.read()

    return status
